In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-19,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-19,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-19,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-19,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-19,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

In [6]:
encoded_df = pd.get_dummies(df,columns=["home_ownership", "verification_status","pymnt_plan","hardship_flag","debt_settlement_flag","next_pymnt_d","application_type","issue_d", "initial_list_status"])
encoded_df.head()

,loan_amnt,int_rate,installment,annual_inc,loan_status,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,...,debt_settlement_flag_N,next_pymnt_d_Apr-19,next_pymnt_d_May-19,application_type_Individual,application_type_Joint App,issue_d_Feb-19,issue_d_Jan-19,issue_d_Mar-19,initial_list_status_f,initial_list_status_w
0,10500.0,0.1719,375.35,66000.0,low_risk,27.24,0.0,0.0,8.0,0.0,...,1,0,1,1,0,0,0,1,0,1
1,25000.0,0.2000,929.09,105000.0,low_risk,20.23,0.0,0.0,17.0,1.0,...,1,0,1,1,0,0,0,1,0,1
2,20000.0,0.2000,529.88,56000.0,low_risk,24.26,0.0,0.0,8.0,0.0,...,1,0,1,1,0,0,0,1,0,1
3,10000.0,0.1640,353.55,92000.0,low_risk,31.44,0.0,1.0,10.0,1.0,...,1,0,1,1,0,0,0,1,0,1
4,22000.0,0.1474,520.39,52000.0,low_risk,18.76,0.0,1.0,14.0,0.0,...,1,0,1,1,0,0,0,1,0,1

# Split the Data into Training and Testing

In [7]:
# Create our features
# Referenced Code from Susie Xia's "credit_risk_resampling.ipynb" file on GitHub to correct syntax error.
X = encoded_df.drop(columns="loan_status")

# Create our target
y = encoded_df["loan_status"]

In [8]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,debt_settlement_flag_N,next_pymnt_d_Apr-19,next_pymnt_d_May-19,application_type_Individual,application_type_Joint App,issue_d_Feb-19,issue_d_Jan-19,issue_d_Mar-19,initial_list_status_f,initial_list_status_w
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,1.0,0.383161,0.616839,0.860340,0.139660,0.371696,0.451066,0.177238,0.123879,0.876121
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.0,0.486161,0.486161,0.346637,0.346637,0.483261,0.497603,0.381873,0.329446,0.329446
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,1.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,1.0,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,1.0,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
# Referenced code from Module 17
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78, stratify=y)
X_train.shape

(51612, 95)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [11]:
# Resample the training data with the BalancedRandomForestClassifier
# Referenced code from Will Willis' "credit_risk_ensemble.ipynb" file to correct syntax.
from imblearn.ensemble import BalancedRandomForestClassifier
model = BalancedRandomForestClassifier(random_state=1)
model = model.fit(X_train, y_train)
model

BalancedRandomForestClassifier(random_state=1)

In [12]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)

balanced_accuracy_score(y_test, y_pred)

0.8061629017247423

In [13]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   63,    24],
       [ 1914, 15204]], dtype=int64)

In [14]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.72      0.89      0.06      0.80      0.63        87
   low_risk       1.00      0.89      0.72      0.94      0.80      0.65     17118

avg / total       0.99      0.89      0.72      0.94      0.80      0.65     17205

In [15]:
# List the features sorted in descending order by feature importance
importances = model.feature_importances_
sorted(zip(model.feature_importances_, X.columns), reverse=True)

[(0.07468109513934523, 'total_rec_prncp'),
 (0.06351557143999598, 'last_pymnt_amnt'),
 (0.061393089156735824, 'total_pymnt_inv'),
 (0.05765552552903142, 'total_pymnt'),
 (0.044867894987521265, 'total_rec_int'),
 (0.029793552314861062, 'int_rate'),
 (0.02587419458069609, 'issue_d_Jan-19'),
 (0.01820411124110668, 'installment'),
 (0.017556891119917897, 'max_bal_bc'),
 (0.016077139613319413, 'out_prncp_inv'),
 (0.0160560529041853, 'il_util'),
 (0.016045567093741796, 'avg_cur_bal'),
 (0.01576351462633056, 'dti'),
 (0.015715722574376076, 'out_prncp'),
 (0.01525175772090346, 'mo_sin_old_rev_tl_op'),
 (0.01468135145173301, 'all_util'),
 (0.014504479422833352, 'issue_d_Mar-19'),
 (0.014265345692157715, 'total_rev_hi_lim'),
 (0.014082592311799152, 'tot_cur_bal'),
 (0.013362826951516922, 'mths_since_recent_bc'),
 (0.013199222561383029, 'total_il_high_credit_limit'),
 (0.012706091855981814, 'mths_since_rcnt_il'),
 (0.01262233914583699, 'mo_sin_old_il_acct'),
 (0.012583542276024318, 'bc_open_to_buy'),
 (0.012446175465882548, 'annual_inc'),
 (0.01239464071865172, 'num_il_tl'),
 (0.012242382043735794, 'bc_util'),
 (0.01216164965470398, 'total_acc'),
 (0.012092126458666353, 'mths_since_recent_inq'),
 (0.012036212602550854, 'revol_bal'),
 (0.011769268095471117, 'total_bal_il'),
 (0.011765057928848365, 'tot_hi_cred_lim'),
 (0.011668978530963818, 'total_bc_limit'),
 (0.011420208298102688, 'loan_amnt'),
 (0.011235832673462547, 'total_bal_ex_mort'),
 (0.010453861888935071, 'num_rev_accts'),
 (0.010447027726227427, 'open_acc'),
 (0.01021449708246348, 'num_sats'),
 (0.01001408297879423, 'mo_sin_rcnt_tl'),
 (0.009768530571756154, 'pct_tl_nvr_dlq'),
 (0.009359753425797398, 'inq_last_12m'),
 (0.009304516273107372, 'acc_open_past_24mths'),
 (0.008767740357751715, 'open_il_24m'),
 (0.00863248955034735, 'total_rec_late_fee'),
 (0.008557849235312717, 'mo_sin_rcnt_rev_tl_op'),
 (0.008324774503788948, 'inq_fi'),
 (0.007972932937273133, 'num_bc_tl'),
 (0.007818348141664311, 'issue_d_Feb-19'),
 (0.007715315138046706, 'num_op_rev_tl'),
 (0.007669387720111469, 'total_cu_tl'),
 (0.007590131003013428, 'num_actv_rev_tl'),
 (0.007481089805396563, 'num_bc_sats'),
 (0.007226025175655075, 'open_acc_6m'),
 (0.006978706362392284, 'next_pymnt_d_Apr-19'),
 (0.006934907267571673, 'num_rev_tl_bal_gt_0'),
 (0.006860587152532226, 'num_actv_bc_tl'),
 (0.006785239008483451, 'mort_acc'),
 (0.006541528986234917, 'open_act_il'),
 (0.0063129194516174485, 'next_pymnt_d_May-19'),
 (0.005920213071033595, 'open_rv_24m'),
 (0.005586480514204097, 'percent_bc_gt_75'),
 (0.005576493002823409, 'num_tl_op_past_12m'),
 (0.0050734999795263, 'open_il_12m'),
 (0.004762698147673937, 'inq_last_6mths'),
 (0.003898228495709308, 'open_rv_12m'),
 (0.003205595246612539, 'delinq_2yrs'),
 (0.0030114053230519476, 'tot_coll_amt'),
 (0.0029926664952985753, 'num_accts_ever_120_pd'),
 (0.0020478089003949664, 'verification_status_Source Verified'),
 (0.002040029819588346, 'pub_rec_bankruptcies'),
 (0.0019846187629177035, 'verification_status_Verified'),
 (0.0019158698554589551, 'verification_status_Not Verified'),
 (0.001815657020711037, 'application_type_Individual'),
 (0.0016334338545966472, 'num_tl_90g_dpd_24m'),
 (0.0012967217246828294, 'application_type_Joint App'),
 (0.001275302339399412, 'initial_list_status_w'),
 (0.00124630553687415, 'home_ownership_MORTGAGE'),
 (0.0011526157751463736, 'home_ownership_OWN'),
 (0.0010771454946977071, 'initial_list_status_f'),
 (0.0010465801724230369, 'pub_rec'),
 (0.000877422880201008, 'home_ownership_RENT'),
 (0.0006530186926310791, 'collections_12_mths_ex_med'),
 (0.0003279839413014063, 'home_ownership_ANY'),
 (0.00015795902639299724, 'chargeoff_within_12_mths'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [16]:
# Train the EasyEnsembleClassifier
# Referenced code from Edward Rivera's "credit_risk_ensemble.ipynb" file from GitHub for details on the 
# EasyEnsembleClassifier model and parameters.
from imblearn.ensemble import EasyEnsembleClassifier
eec = EasyEnsembleClassifier(random_state=1)
eec.fit(X_train, y_train)

y_pred_eec = eec.predict(X_test)

In [17]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)

balanced_accuracy_score(y_test, y_pred)

0.8061629017247423

In [18]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   63,    24],
       [ 1914, 15204]], dtype=int64)

In [19]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.72      0.89      0.06      0.80      0.63        87
   low_risk       1.00      0.89      0.72      0.94      0.80      0.65     17118

avg / total       0.99      0.89      0.72      0.94      0.80      0.65     17205